const { test, expect } = require('@playwright/test')
const path = require('path')

// End-to-end for the Silver Pines catalog vendor (a pickup-only, admin-featured used-goods shop):
//   1. the owner imports their product + opening-stock list from the filled Excel template
//   2. those products appear in the PUBLIC (unauthenticated) marketplace because the shop is featured
//   3. checkout stays gated behind login/signup
//
// Vendor seeded out-of-band: entity "Silver Pines" (RETAILER, delivery_mode=PICKUP, is_featured),
// owner bsptours.treks@gmail.com / test1234. Fixture generated by scripts/gen-silver-pines-import.js.

const VENDOR = { email: 'bsptours.treks@gmail.com', password: 'test1234' }
const IMPORT_FILE = path.join(__dirname, '..', 'fixtures', 'silver-pines-import.xlsx')
const KNOWN_PRODUCT = 'King Size Bed (6ft by 6.5ft)'
const EXPECTED_ROWS = 47

async function login(page, { email, password }) {
  await page.goto('/login')
  await page.getByPlaceholder('you@business.bt').waitFor({ state: 'visible' })
  await page.getByPlaceholder('you@business.bt').fill(email)
  await page.getByPlaceholder('••••••••').fill(password)
  await page.getByRole('button', { name: /sign in/i }).click()
  await page.waitForURL((url) => !url.pathname.startsWith('/login'), { timeout: 30000 })
}

test.describe('Silver Pines — vendor product import', () => {
  test.describe.configure({ mode: 'serial' })

  test('owner imports their hotel-items catalog from Excel', async ({ page }) => {
    await login(page, VENDOR)
    await page.goto('/pos/products')

    await page.getByRole('button', { name: /Import/i }).click()
    await expect(page.getByText('Import Products from Excel')).toBeVisible()

    // Upload the filled template → dry-run preview validates every row.
    await page.locator('input[type="file"]').setInputFiles(IMPORT_FILE)
    await expect(page.getByText(new RegExp(`${EXPECTED_ROWS} of ${EXPECTED_ROWS} rows`))).toBeVisible({ timeout: 15000 })

    // Commit the import.
    await page.getByRole('button', { name: new RegExp(`Import ${EXPECTED_ROWS} products`) }).click()
    await expect(page.getByText(new RegExp(`Imported ${EXPECTED_ROWS} product`))).toBeVisible({ timeout: 30000 })
    console.log('VENDOR_IMPORT_OK')

    // Isolation: the vendor's catalog shows only their own products, not other stores'.
    await page.getByRole('button', { name: /Done/i }).click()
    await expect(page.getByText(KNOWN_PRODUCT).first()).toBeVisible({ timeout: 15000 })
    await expect(page.getByText('Druk 1100 Generator')).toHaveCount(0)  // a different store's product
    console.log('VENDOR_ISOLATION_OK')
  })
})

test.describe('Silver Pines — public featured catalog', () => {
  // Unauthenticated visitor.
  test.use({ storageState: { cookies: [], origins: [] } })

  test('featured shop + its products show without login', async ({ page }) => {
    await page.goto('/shop')
    // Logged-out marketing hero (browse is public).
    await expect(page.getByText(/Sign in \/ Sign up to buy/i)).toBeVisible({ timeout: 15000 })
    // The featured vendor's imported product is visible to anonymous shoppers.
    await expect(page.getByText(KNOWN_PRODUCT).first()).toBeVisible({ timeout: 15000 })
    console.log('PUBLIC_CATALOG_OK')
  })

  test('checkout is gated behind login', async ({ page }) => {
    await page.goto('/shop/checkout')
    await page.waitForURL(/\/login/, { timeout: 15000 })
    expect(page.url()).toContain('/login')
    console.log('CHECKOUT_GATED_OK')
  })
})
